# Wildfly server with additional configurations

FROM jboss/wildfly:8.2.1.Final

MAINTAINER Lucas Russo

ENV POSTGRES_VERSION_DOWN ENV_POSTGRES_VERSION
ENV CCDB_VERSION_DOWN ENV_CCDB_VERSION

# Add our custom configuration
ADD configuration /opt/jboss/wildfly/standalone/configuration/

# User root user to install software
USER root

# Create default admin user
RUN OPTNAMESERVER
    /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

# Switch back to jboss user
USER jboss

## Deploy JDBC Postgres
#COPY deploy/postgresql-$POSTGRES_VERSION_DOWN.jar /opt/jboss/wildfly/standalone/deployments/

## Deploy App
#COPY deploy/ccdb-ws-$CCDB_VERSION_DOWN.war /opt/jboss/wildfly/standalone/deployments/

# Deploy everything
ADD deploy /opt/jboss/wildfly/standalone/deployments/

# Copy possible entrypoint for user use
COPY scripts/wait-for-it/wait-for-it.sh /
